name: Deploy

on:
  push:
    branches:
      - master  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and run deploy.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PATH }}
            ./${{ secrets.SCRIPT }}
